// "use client";
import { Inter } from "next/font/google";
import "./sass/page.scss";
import img from "../public/favicon.png";

const inter = Inter({ subsets: ["latin"] });
import { Header } from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: img.src,
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body>
        <div className="wrapper">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
